// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortlandAnimalShelterApi.Models;

namespace PortlandAnimalShelter.Migrations
{
    [DbContext(typeof(PortlandAnimalShelterApiContext))]
    [Migration("20210122170608_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortlandAnimalShelterApi.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdoptFee");

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Color");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Personality");

                    b.Property<int>("Weight");

                    b.HasKey("CatId");

                    b.ToTable("Cats");
                });

            modelBuilder.Entity("PortlandAnimalShelterApi.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdoptFee");

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Color");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Personality");

                    b.Property<int>("Weight");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
