// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortlandAnimalShelterApi.Models;

namespace PortlandAnimalShelter.Migrations
{
    [DbContext(typeof(PortlandAnimalShelterApiContext))]
    [Migration("20210122235042_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortlandAnimalShelterApi.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("AdoptFee");

                    b.Property<int>("Age");

                    b.Property<string>("Breed")
                        .IsRequired();

                    b.Property<string>("Color")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Personality")
                        .IsRequired();

                    b.Property<float>("Weight");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            AdoptFee = 25f,
                            Age = 10,
                            Breed = "Short-Hair Domestic",
                            Color = "Grey, White",
                            Gender = "Female",
                            Name = "Bulma",
                            Personality = "affectionate and social",
                            Weight = 11f
                        },
                        new
                        {
                            CatId = 2,
                            AdoptFee = 100f,
                            Age = 12,
                            Breed = "Short-Hair Domestic",
                            Color = "Black with stars",
                            Gender = "Male",
                            Name = "Dusty",
                            Personality = "loyal, independent",
                            Weight = 8f
                        },
                        new
                        {
                            CatId = 3,
                            AdoptFee = 170f,
                            Age = 6,
                            Breed = "Short-Hair Domestic",
                            Color = "Orange Tabby",
                            Gender = "Female",
                            Name = "Spot",
                            Personality = "cautious of strangers, affectionate",
                            Weight = 8f
                        });
                });

            modelBuilder.Entity("PortlandAnimalShelterApi.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("AdoptFee");

                    b.Property<int>("Age");

                    b.Property<string>("Breed")
                        .IsRequired();

                    b.Property<string>("Color")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Personality")
                        .IsRequired();

                    b.Property<float>("Weight");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            AdoptFee = 250f,
                            Age = 3,
                            Breed = "Pembroke Corgi",
                            Color = "Red",
                            Gender = "Male",
                            Name = "Ein",
                            Personality = "affectionate and social",
                            Weight = 27f
                        },
                        new
                        {
                            DogId = 2,
                            AdoptFee = 200f,
                            Age = 8,
                            Breed = "Shiba Inu",
                            Color = "Red, Tan",
                            Gender = "Male",
                            Name = "Hachiko",
                            Personality = "loyal, independent",
                            Weight = 20f
                        },
                        new
                        {
                            DogId = 3,
                            AdoptFee = 170f,
                            Age = 7,
                            Breed = "Siberian Husky",
                            Color = "Black, White",
                            Gender = "Male",
                            Name = "Balto",
                            Personality = "active, loyal, strong willed",
                            Weight = 48f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
